### ISSUE TITLE
Use const generics

### ISSUE THREAD

**Issue by vorner** [vorner/slipstream#5]
The MVP const generics are coming Real Soon. They might be easier for the compiler to work with than the GenericArray thing (and for humans too), so it might make sense to try switching over to them.

**Comment by vorner** [comment]
The constgen branch contains the ported code. It's waiting there for 1.51 to make it stable.

The code is simpler, but the compiler doesn't seem to generate a fast code more often.

**Comment by HadrienG2** [comment]
I think this is now covered and can be closed?

**Comment by vorner** [comment]
You're right, thanks for pointing it out.
